services:
    swiftmailer.transport.eventdispatcher.slowprog_sparkpost: 
        class: Swift_Events_SimpleEventDispatcher
    
    swiftmailer.mailer.transport.slowprog_sparkpost:
        class: SlowProg\SparkPostSwiftMailer\SwiftMailer\SparkPostTransport
        arguments:
            - "@swiftmailer.transport.eventdispatcher.slowprog_sparkpost"